config/routes.rb
TamenchanServer::Application.routes.draw do
  
  resources :hiscores

  get 'hiscorelist' => 'hiscore_trans#index'

  post 'hiscorelist' => 'hiscore_trans#create'
  
  
  root :to => 'hiscores#publicindex'
  

end

app/models/hiscore.rb
class Hiscore < ActiveRecord::Base
  attr_accessible :achieved_date, :devid, :name, :rank, :score, :gamelevel
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/hiscore_trans_controller.rb
class HiscoreTransController < ApplicationController

  RANKING_NUM = 50 #ランキング表示する数
  OUT_OF_RANKING = 99999
  
  def index
    render json: gethiscorelist
  end

  def create
    gamelevel = params[:gamelevel]
    if gamelevel == nil
      gamelevel = 1
    end
    
    id = []
    devid = []
    name = []
    score = []
    date = []
    
    id[0] = params[:id0]
    devid[0] = params[:devid0]
    name[0] = params[:name0]
    score[0] = params[:score0]
    date[0] = params[:date0]
    
    id[1] = params[:id1]
    devid[1] = params[:devid1]
    name[1] = params[:name1]
    score[1] = params[:score1]
    date[1] = params[:date1]

    id[2] = params[:id2]
    devid[2] = params[:devid2]
    name[2] = params[:name2]
    score[2] = params[:score2]
    date[2] = params[:date2]

    id[3] = params[:id3]    
    devid[3] = params[:devid3]
    name[3] = params[:name3]
    score[3] = params[:score3]
    date[3] = params[:date3]

    id[4] = params[:id4]
    devid[4] = params[:devid4]
    name[4] = params[:name4]
    score[4] = params[:score4]
    date[4] = params[:date4]

    hiscore = []
    for i in 0..4
      hiscore[i] = Hiscore.new
      
      if id[i] != nil
        hiscore[i].id = id[i]
      elsif
        id[i] = 0; #ダミーID
      end
      
      hiscore[i].devid = devid[i]
      hiscore[i].name = name[i]
      hiscore[i].score = score[i]
      hiscore[i].achieved_date = date[i]
      hiscore[i].gamelevel = gamelevel
      
      hiscorelist = Hiscore.find(:all, 
        :conditions => ["gamelevel = ? and score > ? and id <> ?", gamelevel, score[i], id[i]])
      hiscore[i].rank = hiscorelist.length + 1
      
      if hiscore[i].id == nil
        hiscore[i].save
      end
      
      # 順位がランキング数より下なら、ランキング外の順位を返す（保存後に行う）
      if hiscore[i].rank > RANKING_NUM
        hiscore[i].rank = OUT_OF_RANKING
      end
    end

    render json: hiscore
  end

  def gethiscorelist
    gamelevel = params[:gamelevel]
    if gamelevel == nil
      gamelevel = 1
    end
    
    hiscorelist = Hiscore.find(:all,
      :conditions => { :gamelevel => gamelevel }, :order => 'score desc, id', :limit => RANKING_NUM )
    
    num = 1
    rank = 1
    score = 0
    
    for hiscore in hiscorelist do
      if hiscore.score == score 
        hiscore.rank = rank
      else 
        hiscore.rank = num
        rank = num
        score = hiscore.score
      end
      num += 1
    end
    
    return hiscorelist
  end

end

app/controllers/hiscores_controller.rb
class HiscoresController < ApplicationController

  def publicindex
    @hiscores_easy = Hiscore.find(:all,
      :conditions => { :gamelevel => 0 }, :order => 'score desc, id', :limit => '50' )
    
    @hiscores_normal = Hiscore.find(:all,
      :conditions => { :gamelevel => 1 }, :order => 'score desc, id', :limit => '50' )
    
    @hiscores_hard = Hiscore.find(:all,
      :conditions => { :gamelevel => 2 }, :order => 'score desc, id', :limit => '50' )
    
    calcrank(@hiscores_easy)
    calcrank(@hiscores_normal)
    calcrank(@hiscores_hard)
  end
  
  def calcrank(hiscorelist)
    num = 1
    rank = 1
    score = 0
    
    for hiscore in hiscorelist do
      if hiscore.score == score 
        hiscore.rank = rank
      else 
        hiscore.rank = num
        rank = num
        score = hiscore.score
      end
      num += 1
    end
    
    return hiscorelist
  end



  # GET /hiscores
  # GET /hiscores.json
  def index
#    @hiscores = Hiscore.all
    sort = params[:sort]
    if sort == "created"
      @hiscores = Hiscore.find(:all, :order => 'created_at desc')
    elsif 
      @hiscores = Hiscore.find(:all, :order => 'gamelevel, score desc, id')
    end
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @hiscores }
    end
  end
  

  # GET /hiscores/1
  # GET /hiscores/1.json
  def show
    @hiscore = Hiscore.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @hiscore }
    end
  end

  # GET /hiscores/new
  # GET /hiscores/new.json
  def new
    @hiscore = Hiscore.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @hiscore }
    end
  end

  # GET /hiscores/1/edit
  def edit
    @hiscore = Hiscore.find(params[:id])
  end

  # POST /hiscores
  # POST /hiscores.json
  def create
    @hiscore = Hiscore.new(params[:hiscore])

    respond_to do |format|
      if @hiscore.save
        format.html { redirect_to @hiscore, notice: 'Hiscore was successfully created.' }
        format.json { render json: @hiscore, status: :created, location: @hiscore }
      else
        format.html { render action: "new" }
        format.json { render json: @hiscore.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /hiscores/1
  # PUT /hiscores/1.json
  def update
    @hiscore = Hiscore.find(params[:id])

    respond_to do |format|
      if @hiscore.update_attributes(params[:hiscore])
        format.html { redirect_to @hiscore, notice: 'Hiscore was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @hiscore.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hiscores/1
  # DELETE /hiscores/1.json
  def destroy
    @hiscore = Hiscore.find(params[:id])
    @hiscore.destroy

    respond_to do |format|
      format.html { redirect_to hiscores_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hiscore_trans_helper.rb
module HiscoreTransHelper
end

app/helpers/hiscores_helper.rb
module HiscoresHelper
end

app/views/hiscores/_form.html.erb
<%= form_for(@hiscore) do |f| %>
  <% if @hiscore.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hiscore.errors.count, "error") %> prohibited this hiscore from being saved:</h2>

      <ul>
      <% @hiscore.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :score %><br />
    <%= f.number_field :score %>
  </div>
  <div class="field">
    <%= f.label :rank %><br />
    <%= f.number_field :rank %>
  </div>
  <div class="field">
    <%= f.label :devid %><br />
    <%= f.text_field :devid %>
  </div>
  <div class="field">
    <%= f.label :achieved_date %><br />
    <%= f.datetime_select :achieved_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hiscores/edit.html.erb
<h1>Editing hiscore</h1>

<%= render 'form' %>

<%= link_to 'Show', @hiscore %> |
<%= link_to 'Back', hiscores_path %>

app/views/hiscores/index.html.erb
<h1>Listing hiscores</h1>

<table>
  <tr>
    <th>Level</th>
    <th>Name</th>
    <th>Score</th>
    <th>Rank</th>
    <th>Devid</th>
    <th>Achieved date</th>
    <th>Created date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @hiscores.each do |hiscore| %>
  <tr>
    <td><%= hiscore.gamelevel %></td>
    <td><%= hiscore.name %></td>
    <td><%= hiscore.score %></td>
    <td><%= hiscore.rank %></td>
    <td><%= hiscore.devid %></td>
    <td><%= hiscore.achieved_date %></td>
    <td><%= hiscore.created_at %></td>
    <td><%= link_to 'Show', hiscore %></td>
    <td><%= link_to 'Edit', edit_hiscore_path(hiscore) %></td>
    <td><%= link_to 'Destroy', hiscore, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Hiscore', new_hiscore_path %>

app/views/hiscores/new.html.erb
<h1>New hiscore</h1>

<%= render 'form' %>

<%= link_to 'Back', hiscores_path %>

app/views/hiscores/publicindex.html.erb
<h1>ためんちゃん　みんなのハイスコア</h1>

<div id="easy">

<h2>初級</h2>

<table class="hiscoretable">
  <tr>
    <th class="rank">順位</th>
    <th class="name">名前</th>
    <th class="score">得点</th>
    <th class="date">日付</th>
  </tr>

<% @hiscores_easy.each do |hiscore| %>
  <tr>
    <td class="rank"><%= hiscore.rank %>位</td>
    <td class="name"><%= hiscore.name %></td>
    <td class="score"><%= hiscore.score %>点</td>
    <td class="date"><%= hiscore.achieved_date.localtime.strftime('%Y/%m/%d') %></td>
  </tr>
<% end %>
</table>

</div>

<div id="normal">

<h2>中級</h2>

<table class="hiscoretable">
  <tr>
    <th class="rank">順位</th>
    <th class="name">名前</th>
    <th class="score">得点</th>
    <th class="date">日付</th>
  </tr>

<% @hiscores_normal.each do |hiscore| %>
  <tr>
    <td class="rank"><%= hiscore.rank %>位</td>
    <td class="name"><%= hiscore.name %></td>
    <td class="score"><%= hiscore.score %>点</td>
    <td class="date"><%= hiscore.achieved_date.localtime.strftime('%Y/%m/%d') %></td>
  </tr>
<% end %>
</table>

</div>

<div id="hard">

<h2>上級</h2>

<table class="hiscoretable">
  <tr>
    <th class="rank">順位</th>
    <th class="name">名前</th>
    <th class="score">得点</th>
    <th class="date">日付</th>
  </tr>

<% @hiscores_hard.each do |hiscore| %>
  <tr>
    <td class="rank"><%= hiscore.rank %>位</td>
    <td class="name"><%= hiscore.name %></td>
    <td class="score"><%= hiscore.score %>点</td>
    <td class="date"><%= hiscore.achieved_date.localtime.strftime('%Y/%m/%d') %></td>
  </tr>
<% end %>
</table>

</div>

app/views/hiscores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @hiscore.name %>
</p>

<p>
  <b>Score:</b>
  <%= @hiscore.score %>
</p>

<p>
  <b>Rank:</b>
  <%= @hiscore.rank %>
</p>

<p>
  <b>Devid:</b>
  <%= @hiscore.devid %>
</p>

<p>
  <b>Achieved date:</b>
  <%= @hiscore.achieved_date %>
</p>


<%= link_to 'Edit', edit_hiscore_path(@hiscore) %> |
<%= link_to 'Back', hiscores_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ためんちゃん　ー麻雀力強化アプリー</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>